[tasks.run]
category = "develop"
description = "Run bot on local machine."
script = ['''
cargo run
''']

[tasks.build]
category = "develop"
args = ["build", "--release"]
description = "Build"

[tasks.run_container]
category = "develop"
dependencies = ["build_container"]
description = "Run bot in container."
script = ['''
docker rm -f mpubot
docker run -d --name mpubot main-power-up-bot
''']

[tasks.build_container]
category = "develop"
description = "Build docker image."
script = ['''
docker build -t main-power-up-bot .
''']
