[tasks.run]
category = "develop"
description = "Run bot on local machine."
script = ['''
cargo run
''']

[tasks.build]
category = "develop"
args = ["build", "--release"]
description = "Build"

[tasks.run_container]
category = "develop"
dependencies = ["build_container"]
description = "Run bot in container."
script = ['''
docker rm -f mpubot
docker run -d --name mpubot main-power-up-bot
''']

[tasks.build_container]
category = "develop"
description = "Build docker image."
script = ['''
docker build -t main-power-up-bot .
''']

[tasks.format_check]
description = "Check code format."
category = "develop"
command = "cargo"
args = ["fmt", "--check"]

[tasks.lint]
description = "Run linter"
category = "develop"
command = "cargo"
args = ["check"]

[tasks.test]
description = "Run all tests."
category = "develop"
command = "cargo"
args = ["test"]

[tasks.ci]
description = "ci"
category = "develop"
dependencies = ["format_check", "lint", "test"]
